### ISSUE TITLE
question when running

### ISSUE THREAD

**Issue by hongxianglics** [prokia/BioNavi-NP#3]
Hi,

When I was running the `run_biosynthesis.py `file, I got this error: `pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found` and I thought this is because there is only cpu on my computer.

Could you help me figure out this problem and I wonder is there a cpu version to run your code?

Thanks!

**Comment by prokia** [comment]
Unfortunately, to my knowledge, there is no good way to run Transformer models with only CPU available. I would suggest trying to use a cloud service such as colab for running this code.
