### ISSUE TITLE
no module found error

### ISSUE THREAD

**Issue by hongxianglics** [prokia/BioNavi-NP#5]
Hi,

When I was running the model, I met the module not found error(see figure below). 
it said the module`mlp_retrosyn` can not be found, I checked the file and found the file is in a different folder, so I add the full path of this module to the python file`prepare_utils.py` when import the `mlp_retrosyn` module. What I did is change the file `prepare_utils.py` line 9 `from mlp_retrosyn.mlp_inference import MLPModel` to  `from retro_star.packages.mlp_retrosyn.mlp_retrosyn.mlp_inference import MLPModel`  This problem was solved.
<img width="721" alt="no_module_found" src="https://user-images.githubusercontent.com/104338096/214924006-48c7ca54-ad08-4667-904a-ae6abdef1bbd.PNG">

However, other modules still can not be found e.g.`rdchiral` (see figure). So I am wondering, instead of adding the full path to the python file mannually to import the missing module, is there a better solution?

Thanks in advance!

**Comment by prokia** [comment]
You should run '''bash install.sh''' to install all the packages first.

**Comment by hongxianglics** [comment]
That works! Thanks!
